# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghcontrib', '0003_repo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=255)),
                ('repo',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='ghcontrib.Repo')),
            ],
        ),
    ]
