# Generated by Django 2.0.2 on 2018-02-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghcontrib', '0007_user_loaded_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.TextField(),
        ),
    ]
