# Generated by Django 2.0.2 on 2018-02-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubcontrib', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loaded_initial_data',
            field=models.BooleanField(default=False),
        ),
    ]
