# Generated by Django 3.2 on 2021-04-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("githubcontrib", "0008_auto_20180214_2005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
