# Generated by Django 4.0.4 on 2022-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubcontrib', '0010_user_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_name_repo'),
        ),
    ]
