# Generated by Django 4.0.5 on 2022-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubcontrib', '0011_alter_commit_url_repo_unique_user_name_repo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repo',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='repo',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
