---
name: DB Backup
on:
  schedule:
    - cron: "0 9 * * *" # Runs at 09:00 UTC (05:00 EDT) daily
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  db_backup:
    name: DB Backup
    runs-on: ubuntu-latest
    env:
      PROJECT: githubcontrib
      DB_HOST: mysql.samarchyan.me
      SPACE_NAME: scrap-db-backups
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/New_York"

      - name: Backup DB
        run: make backup-db
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Upload backup
        uses: BetaHuhn/do-spaces-action@v2.0.118
        with:
          access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          secret_key: ${{ secrets.SPACES_SECRET_KEY }}
          space_name: ${{ env.SPACE_NAME }}
          space_region: nyc3
          out_dir: ${{ env.PROJECT }}
          source: upload
