---
name: Reusable Test
on:
  workflow_call:
jobs:
  reusable_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Use npm cache
        uses: actions/cache@v4.2.2
        with:
          path: ~/.npm
          key: npm

      - name: Use node_modules cache
        uses: actions/cache@v4.2.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-test.json') }}
          restore-keys: |
            node_modules-

      - name: Use pip cache
        uses: actions/cache@v4.2.2
        with:
          path: ~/.cache/pip
          key: pip

      - name: Use tox cache
        uses: actions/cache@v4.2.2
        with:
          path: .tox
          key: tox-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}

      - name: Install linters binaries
        run: make install-linters-binaries

      - name: Install tox
        run: pip install tox

      - name: Install python requirements
        run: tox -e py-requirements

      - name: Install js dependencies
        run: |
          mv package-test.json package.json
          npm install

      - name: Run tests
        run: make test

      - name: Run codecov
        uses: codecov/codecov-action@v5.4.0
